import type { Metadata } from "next";
import '@/shared/styles/global.css';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{`
          @view-transition {
            navigation: auto;
          }
          
          /* Предотвращаем мигание при загрузке изображений */
          img {
            image-rendering: crisp-edges;
            image-rendering: -webkit-optimize-contrast;
          }
        `}</style>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
